<?php

/**
 * @file
 * Contains aspambot.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function aspambot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aspambot module.
    case 'help.page.aspambot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A pretentious spam blocker.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function aspambot_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (function_exists('geoip_country_code_by_name')) {
    $user = \Drupal::currentUser();
    if (!$user->isAuthenticated()) {
      $banned_countries = \Drupal::config('aspambot.settings')->get('countries');
      $reverse = \Drupal::config('aspambot.settings')->get('reverse');
      $ip = \Drupal::request()->getClientIP();
      $country = geoip_country_code_by_name($ip);
      if ($reverse) {
        if (!in_array($country, $banned_countries)) {
          $form['#access'] = FALSE;
          $form['#markup'] = '';
          $form['#cache'] = [
            'contexts' => [],
            'max-age' => 0,
          ];
        }
      }
      else {
        if (in_array($country, $banned_countries)) {
          $form['#access'] = FALSE;
          $form['#markup'] = '';
          $form['#cache'] = [
            'contexts' => [],
            'max-age' => 0,
          ];
        }
      }
    }
  }
  else {
    drupal_set_message(t('PHP GeoIp Extension is not installed but is required.'), 'error');
  }
}
